name: FitnessApp
description: A Flutter sample to demonstrate isolates
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  settings_ui: ^2.0.2
  flutter:
    sdk: flutter
  provider: ^6.0.2
  table_calendar: ^3.0.6
  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.0

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/records.json

